version: '2'

services:
  ddns:
    restart: unless-stopped
    build:
      context: ..
      dockerfile: docker/ddns/Dockerfile
    depends_on:
      - redis
    environment:
      DDNS_DOMAIN: d.example.net
      DDNS_SOA_DOMAIN: soa.example.net

  powerdns:
    restart: unless-stopped
    build:
      context: powerdns/
      dockerfile: Dockerfile
    depends_on:
      - ddns
    environment:
      PDNS_REMOTE_HTTP_HOST: "ddns:8057"

  redis:
    restart: unless-stopped
    image: redis:4-alpine